# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'bar-frontend'
  dockerHub: 'barfrontend.azurecr.io'

steps:
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    repository: $(imageName)
    command: buildAndPush
    Dockerfile: Dockerfile
    containerRegistry: $(dockerHub)
    tags: |
      test1

